spring.application.name=api

spring.config.import=optional:file:.env[.properties]


spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS
app.cors.allowed-origins=http://localhost:5173

# Rate limiting
app.rate-limit.login.max-attempts=5
app.rate-limit.login.window-seconds=60