-- V1__baseline_schema.sql
-- Baseline of existing schema (Hibernate ddl-auto=update). Verified 2026-08-16.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    name          VARCHAR(255),
    email         VARCHAR(255),
    password      VARCHAR(255),
    role          VARCHAR(255),
    firebase_uid  VARCHAR(255)
);

CREATE TABLE tutorials (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    title       VARCHAR(255),
    description VARCHAR(255),
    status      VARCHAR(255)
);

CREATE TABLE tutorial_steps (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    tutorial_id  BIGINT,
    step_number  INTEGER,
    instruction  VARCHAR(255),
    image_url    VARCHAR(255),
    CONSTRAINT fk_tutorial_steps_tutorial
        FOREIGN KEY (tutorial_id) REFERENCES tutorials(id)
);